defaults:
  - default
  - override dataset: cancer
  - override model: segformer
  - override lr_scheduler: redplat
  - override loss: dice_ce

logger:
  use_env_token: True
  project: andreaf/polarlows

checkpoints: True

run_tags: ['cancer']
