defaults:
  - default
  - override dataset: cancer
  - override model: segformer
  - override lr_scheduler: redplat
  - override loss: dice_ce #

logger:
  use_env_token: True
  project: andreaf/polarlows

checkpoints: True

dataset:
  num_labels: 5 #
  # class_weight: [0.2, 1.0, 0.8, 0.3]

predict:
  gt_folder: data/bus/gt_masks

run_tags: ['cancer']
