defaults:
  - _self_
  - logger: neptune
  - dataset: voc
  - model: segformer
  - optimizer: adamW
  - lr_scheduler: cosine
  - loss: custom_dice_ce

#### Log and sweep params 
hydra:
  run:
    dir: logs/${dataset.name}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${dataset.name}/${model.name}/${hydra.job.num}

#### Experiment params 
tags: ${cat:${default_tags},${run_tags}}

default_tags:
  - ${model.name}
  - ${dataset.name}

run_tags: ['']

seed: 42

workers: 16
log_grad_norm: False
log_lr: True

plot_preds_at_epoch:
  set: ["val"]
  batch: 2
  samples: 8
  every: 5

#### Training params
batch_size: 16  # This needs to be 16 at most otherwise I run out of CUDA memory.
epochs: 250
patience: 40
limit_train_batches: null
limit_val_batches: null
clip_val: 5.0
checkpoints: False   # save checkpoints while training

monitor: val_f1  # val_loss
mode: max  # min

#### Only for prediction
checkpoint:
  base_folder: "checkpoints/"
  path: "" # Must be specified at runtime. This path is added to the 
           # base_folder path to load the checkpoint.