defaults:
  - default
  - override dataset: polar_lows
  - override model: segformer
  - override lr_scheduler: redplat
  - override loss: dynamic_bootstrap

logger:
  use_env_token: True
  project: andreaf/polarlows

checkpoints: True

run_tags: ['pl']

predict:
  test_image_dir: data/pl/images/test/pos