defaults:
  - default
  - override dataset: voc_binary
  - override model: segformer
  - override lr_scheduler: redplat
  - override loss: dice_ce

logger:
  use_env_token: True
  project: andreaf/polarlows

batch_size: 32

checkpoints: True

run_tags: ['voc']